# Generated by Django 4.2.20 on 2025-04-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='title',
            field=models.CharField(default='Alert Title', max_length=200),
        ),
    ]
