# Generated by Django 4.2.20 on 2025-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='city',
            field=models.CharField(default='New Delhi', max_length=100),
            preserve_default=False,
        ),
    ]
