# Generated by Django 4.2.20 on 2025-04-20 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0002_emergencyalert_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyalert',
            name='level',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='title',
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='expiry_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='After this time alert is discarded'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SeenAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.emergencyalert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'alert')},
            },
        ),
    ]
