# Generated by Django 4.2.20 on 2025-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_remove_emergencyalert_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyalert',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='title',
            field=models.CharField(default='Untitled Alert', max_length=200),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='expiry_time',
            field=models.DateTimeField(),
        ),
    ]
