# Generated by Django 4.2.20 on 2025-04-24 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Include country code, e.g., +919876543210', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{10,15}$')]),
        ),
    ]
