# Generated by Django 4.2.20 on 2025-04-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('pothole', 'Pothole'), ('streetlight', 'Street Light'), ('garbage', 'Garbage'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('location_name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='reported', max_length=20)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reported by')),
            ],
            options={
                'verbose_name': 'Feedback Report',
                'verbose_name_plural': 'Feedback Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes_set', to='feedback.feedbackreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Upvote',
                'verbose_name_plural': 'Feedback Upvotes',
                'unique_together': {('user', 'feedback')},
            },
        ),
        migrations.AddIndex(
            model_name='feedbackreport',
            index=models.Index(fields=['status', 'created_at'], name='feedback_fe_status_119b15_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackreport',
            index=models.Index(fields=['latitude', 'longitude'], name='feedback_fe_latitud_46d784_idx'),
        ),
    ]
