# Generated by Django 4.2.20 on 2025-04-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreport',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedbackreport',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
