# Generated by Django 4.2.20 on 2025-04-06 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback Report', 'verbose_name_plural': 'Feedback Reports'},
        ),
        migrations.RemoveField(
            model_name='feedbackreport',
            name='is_anonymous',
        ),
        migrations.AddField(
            model_name='feedbackreport',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedbackreport',
            name='admin_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedbackreport',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedbackreport',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedbackreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reported by'),
        ),
        migrations.AddIndex(
            model_name='feedbackreport',
            index=models.Index(fields=['status', 'created_at'], name='feedback_fe_status_119b15_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackreport',
            index=models.Index(fields=['latitude', 'longitude'], name='feedback_fe_latitud_46d784_idx'),
        ),
    ]
