# Generated by Django 4.2.20 on 2025-04-19 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_alter_feedbackreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to=settings.AUTH_USER_MODEL, verbose_name='Reported by'),
        ),
    ]
