# Generated by Django 4.2.20 on 2025-04-24 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_feedbackreport_approved_feedbackreport_is_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackreport',
            name='issue_type',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('pothole', 'Pothole'), ('streetlight', 'Street Light'), ('garbage', 'Garbage'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_official', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedbackreport')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
