# Generated by Django 4.2.20 on 2025-04-19 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0003_alter_feedbackreport_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes_set', to='feedback.feedbackreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback Upvote',
                'verbose_name_plural': 'Feedback Upvotes',
                'unique_together': {('user', 'feedback')},
            },
        ),
    ]
