# Generated by Django 4.2.20 on 2025-04-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedbackupvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreport',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
